apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-client
  namespace: anime
  labels:
    app: anime-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-client
  template:
    metadata:
      labels:
        app: anime-client
    spec:
      containers:
        - name: client
          image: fkvivid/anime-recommendation-client:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
