apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-ingress
  namespace: anime
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - anime.vividtemka.com
      secretName: app-tls-bhjmf
  rules:
    - host: anime.vividtemka.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80